# Generated by Django 4.0.1 on 2022-05-15 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.building')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('period_of_day', models.CharField(choices=[('---', '---'), ('Almoço', 'Almoço'), ('Janta', 'Janta')], default=('---', '---'), max_length=100)),
                ('salad', models.CharField(choices=[('---', '---'), ('Alface Crespo', 'Alface Crespo'), ('Mix de Salada', 'Mix de Salada')], default=('---', '---'), max_length=100)),
                ('protein_main', models.CharField(choices=[('---', '---'), ('Carne de Panela', 'Carne de Panela'), ('Frango Frito', 'Frango Frito'), ('Frango Assado', 'Frango Assada'), ('Pernil', 'Pernil')], default=('---', '---'), max_length=100)),
                ('protein_secondary', models.CharField(choices=[('---', '---'), ('Beringela Refogada', 'Beringela Refogada'), ('Bolinho de Grão de Bico', 'Bolinho de Grão de Bico')], default=('---', '---'), max_length=100)),
                ('rice_white', models.BooleanField(default=True)),
                ('rice_brown', models.BooleanField(default=True)),
                ('beans', models.BooleanField(default=True)),
                ('fruit', models.CharField(choices=[('---', '---'), ('Maça', 'Maça'), ('Banana', 'Banana'), ('Melancia', 'Melancia'), ('Pudim', 'Pudim')], default=('---', '---'), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.department')),
            ],
        ),
    ]
