# Generated by Django 4.0.1 on 2022-05-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
