# Generated by Django 4.0.1 on 2022-05-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_availablesubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablesubject',
            name='day_1',
            field=models.CharField(choices=[('---', '---'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], default=('---', '---'), max_length=50),
        ),
        migrations.AddField(
            model_name='availablesubject',
            name='day_1_time_1',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='availablesubject',
            name='day_1_time_2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='availablesubject',
            name='day_2',
            field=models.CharField(choices=[('---', '---'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], default=('---', '---'), max_length=50),
        ),
        migrations.AddField(
            model_name='availablesubject',
            name='day_2_time_1',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='availablesubject',
            name='day_2_time_2',
            field=models.TimeField(null=True),
        ),
    ]
