# Generated by Django 4.0.1 on 2022-05-16 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.period'),
            preserve_default=False,
        ),
    ]
